label: Impostazioni
icon: settings
      
sections:
  section_logo:
    type: fields
    fields:
      logo_headline:
        type: headline
        label: Logo
        width: 1/1
      logo_switch:
        label: Tipologia di logo
        type: radio
        width: 1/2
        options: 
          logo: icona / simbolo
          logotype: tipografia
        columns: 2
        default: logo
        help: Scegli come visualizzare il brand nell'header
      logotype:
        label: Logo tipografico
        type: text
        width: 1/2
        when: 
          logo_switch: logotype
      logo:
        label: Logo Header
        type: files
        width: 1/2
        when: 
          logo_switch: logo
        max: 1
        help: Carica il logo <b>in formato .SVG</b>
      separator_a:
        type: line

  section_search:
    type: fields
    fields:
      search_headline:
        type: headline
        label: Ricerca
        width: 1/1
      ricerche_frequenti:
        label: Ricerche frequenti
        type: structure
        help: Parole chiave suggerite nel pannello di ricerca
        fields:
          testo:
            label: Testo
            type: text
      separator_2:
        type: line

  section_menu:
    type: fields
    fields:
      menu_headline:
        type: headline
        label: Menu principale
        width: 1/1
      menu:
        type: structure
        label: Voci del menu
        help: Gestisci la navigazione principale del sito
        width: 1/1
        fields:
          isMobile:
            type: toggle
            label: Solo mobile?
            width: 1/2
          isExternal:
            type: toggle
            label: Link esterno?
            width: 1/2
          linkTitle:
            type: text
            label: Titolo del link
            width: 1/2
          pageLink:
            label: Pagina associata
            type: pages
            max: 1
            when:
              isExternal: false
          externalLink:
            type: text
            label: Link associato
            when:
              isExternal: true     
      separator_3:
        type: line

  section_footer:
    headline: Footer 
    type: fields
    fields:
      footer_headline:
        type: headline
        label: Footer & Social
        width: 1/1
      footer: fields/footer_layout

  section_extra:
    headline: Configurazioni Avanzate
    type: fields
    fields:
      extra_headline:
        type: headline
        label: Integrazioni & Mappe
        width: 1/1
      mapbox_token: 
        type: text
        label: Mapbox Token
        help: Necessario per le mappe interattive
      marker:
        type: files
        label: Marker di default (Mappe)
        width: 1/2
        max: 1
        help: Carica il marker <b>in formato .SVG</b>